FROM python:3.12-slim

# Install uv (Python dependency manager)
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Install Node.js and pnpm
RUN apt-get update && \
    apt-get install -y curl && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g pnpm && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy Python files and install dependencies
COPY pyproject.toml ./
RUN uv sync

# Copy UI and install JS dependencies
COPY ui ./ui
WORKDIR /app/ui
RUN pnpm install

# Copy the rest of the code
WORKDIR /app
COPY . .

# 设置可配置的环境变量（示例，按需添加/修改）
ARG LLM_BASE_URL
ARG LLM_API_KEY
ARG LLM_MODEL_NAME
ARG KG_LLM_MODEL_NAME
ARG EMBEDDING_BASE_URL
ARG EMBEDDING_API_KEY
ARG MAIN_SERVER_PORT
ARG A2A_SERVER_PORT
ARG VITE_API_SERVER_URL
ARG USE_LOCAL_FS
ARG USE_CACHE
ARG JFS_NAME
ARG JFS_CACHE_DIR
ARG JFS_LOG_FILE
ARG JFS_PID_FILE
ARG JFS_META_URL
ARG JFS_MOUNTPOINT
ARG JFS_TOKEN
ARG USE_LOCAL_GRAPH_STORE
ARG NEBULA_URL
ARG NEBULA_USERNAME
ARG NEBULA_PASSWORD
ARG NEBULA_SPACE
ARG QDRANT_DATABASE_PATH
ARG MCP_CONFIG_FILE

ENV LLM_BASE_URL=${LLM_BASE_URL}
ENV LLM_API_KEY=${LLM_API_KEY}
ENV LLM_MODEL_NAME=${LLM_MODEL_NAME}
ENV KG_LLM_MODEL_NAME=${KG_LLM_MODEL_NAME}
ENV EMBEDDING_BASE_URL=${EMBEDDING_BASE_URL}
ENV EMBEDDING_API_KEY=${EMBEDDING_API_KEY}
ENV MAIN_SERVER_PORT=${MAIN_SERVER_PORT}
ENV A2A_SERVER_PORT=${A2A_SERVER_PORT}
ENV VITE_API_SERVER_URL=${VITE_API_SERVER_URL}
ENV USE_LOCAL_FS=${USE_LOCAL_FS}
ENV USE_CACHE=${USE_CACHE}
ENV JFS_NAME=${JFS_NAME}
ENV JFS_CACHE_DIR=${JFS_CACHE_DIR}
ENV JFS_LOG_FILE=${JFS_LOG_FILE}
ENV JFS_PID_FILE=${JFS_PID_FILE}
ENV JFS_META_URL=${JFS_META_URL}
ENV JFS_MOUNTPOINT=${JFS_MOUNTPOINT}
ENV JFS_TOKEN=${JFS_TOKEN}
ENV USE_LOCAL_GRAPH_STORE=${USE_LOCAL_GRAPH_STORE}
ENV NEBULA_URL=${NEBULA_URL}
ENV NEBULA_USERNAME=${NEBULA_USERNAME}
ENV NEBULA_PASSWORD=${NEBULA_PASSWORD}
ENV NEBULA_SPACE=${NEBULA_SPACE}
ENV QDRANT_DATABASE_PATH=${QDRANT_DATABASE_PATH}
ENV MCP_CONFIG_FILE=${MCP_CONFIG_FILE}

# Install a process manager to run both commands
RUN pip install --no-cache-dir sh

# .env 文件未被 COPY 到镜像，需在运行容器时挂载或指定
# 示例：
# docker run --env-file /path/to/.env your-image
# 或
# docker run -v /path/to/.env:/app/.env your-image

CMD ["sh", "-c", "env | grep -E '^(LLM_BASE_URL|LLM_API_KEY|LLM_MODEL_NAME|KG_LLM_MODEL_NAME|EMBEDDING_BASE_URL|EMBEDDING_API_KEY|MAIN_SERVER_PORT|A2A_SERVER_PORT|VITE_API_SERVER_URL|USE_LOCAL_FS|USE_CACHE|JFS_NAME|JFS_CACHE_DIR|JFS_LOG_FILE|JFS_PID_FILE|JFS_META_URL|JFS_MOUNTPOINT|JFS_TOKEN|USE_LOCAL_GRAPH_STORE|NEBULA_URL|NEBULA_USERNAME|NEBULA_PASSWORD|NEBULA_SPACE|QDRANT_DATABASE_PATH|MCP_CONFIG_FILE)=' > .env && uv run ./main.py & cd ui && pnpm dev"]
