[project]
name = "iosys"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "a2a",
    "dotenv>=0.9.9",
    "fastapi>=0.115.12",
    "langchain-core>=0.3.59",
    "langchain-google-genai>=2.1.4",
    "langchain-openai>=0.3.16",
    "langgraph>=0.4.3",
    "markitdown[all]",
    "openai>=1.75.0",
    "juicefs==5.2.1",
    "networkx>=3.4.2",
    "ipycytoscape>=1.3.3",
    "ipywidgets>=8.1.7",
    "pandas>=2.2.3",
    "ipykernel>=6.29.5",
    "llama-index>=0.12.40",
    "graspologic>=3.4.2.dev5",
    "future>=1.0.0",
    "llama-index-graph-stores-nebula>=0.4.2",
    "nebula3-python>=3.8.3",
    "jupyter-nebulagraph>=0.14.3",
    "juicefs_local==1.3.0",
    "qdrant-client>=1.12.1",
    "llama-index-vector-stores-qdrant>=0.6.0",
]

[tool.uv.sources]
a2a = { path = "a2a_server/a2a-python-sdk", package = false }
markitdown = { path = "parser/markitdown" }
juicefs = { url = "https://static.juicefs.com/misc/juicefs-5.2.1.202506040923-py3-none-any.whl" }
juicefs_local = { path = "jfs/juicefs-1.3.0-sdk" }

[[tool.uv.index]]
url = "https://mirrors.ustc.edu.cn/pypi/simple"
default = true

[tool.ruff]
exclude = [
    "jfs/juicefs-1.3.0-sdk",
    "markitdown",
    "a2a_server/a2a-python-sdk",
]

[dependency-groups]
dev = [
    "uv>=0.7.8",
]
