name: Auto Format with Ruff

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0 

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5

      # Install ruff
      - name: Install ruff
        run: pip install ruff

      # Run ruff
      - name: Run ruff
        run: |
          ruff check --fix
          ruff format

      # Get author email
      - name: Get Author Email
        id: get_author_email
        run: echo "::set-output name=email::$(git log -1 --pretty=format:%ae || echo 'actions@github.com')"

      # Get author name
      - name: Get Author Name
        id: get_author_name
        run: echo "::set-output name=name::$(git log -1 --pretty=format:%an || echo 'GitHub Actions')"

      # Check for changes and push with sufficient permissions
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_email: ${{ steps.get_author_email.outputs.email }}
          author_name: ${{ steps.get_author_name.outputs.name }}
